server:
  port: 9090


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/training
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true


#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:keyclock


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/akshaykk
          jwk-set-uri: http://localhost:8080/realms/akshaykk/protocol/openid-connect/certs


keyclock:
  serverUrl: http://localhost:8080/auth
  realm: master
  username: app-admin
  password: admin
  clientId: 3B7OAFq62Mu47co2i1T6qOIenafJ25Yq

